server:
    port: 8080
    servlet: 
        context-path: /identity

spring:
    datasource: 
        url: "jdbc:mysql://localhost:3306/identity_service"
        username: root
        password: Ipin@2004

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    signerKey: "u53wj5F+GJCe6Zfqd/pmz5L4iQZfhOw+dmhN7XZiPgkmNKVhe6pQzRTwhbjaE9HZ"
    valid-duration: 20 # in second
    refreshable-duration: 120 # in second